name: coffee_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  change_app_package_name: ^1.1.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  mask_text_input_formatter: ^2.5.0
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  image_picker: ^1.0.1
  path_provider: ^2.1.1
  dio: ^5.3.2
  sqflite: ^2.3.0
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  flutter_screenutil: ^5.9.0
  lottie: ^2.6.0
  cached_network_image: ^3.3.0
  zoom_tap_animation: ^1.1.0
  get_it: ^7.6.4
  google_sign_in: ^6.1.5
  dot_navigation_bar: ^1.0.2
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
        - asset: assets/fonts/Raleway/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          style: italic
